### ISSUE TITLE
Wrong SVG <path>s in the logo 

### ISSUE THREAD

**Issue by ezio-melotti** [overthesun/simoc-web#605]
The logo at https://github.com/overthesun/simoc-web/blob/master/src/assets/simoc-logo.svg has 3 `<path>`s that outline the 3 leaves that intersect the blue area on the left.  These paths are set to be white (`#ffffff`), and while this works on a white background, it doesn't on a dark one:
 https://github.com/overthesun/simoc-web/blob/eb51ccaa79c5a2e8bbce84cf94bafc373665f1d3/src/assets/simoc-logo.svg#L132-L136

This is how it looks on a dark background:
![image](https://github.com/overthesun/simoc-web/assets/25624924/03cfb0bf-c297-40e4-8317-40c05bec08f2)

I tried to change to opacity to make them transparent, but they end up showing the blue underneath instead:
![image](https://github.com/overthesun/simoc-web/assets/25624924/946086d2-6d1f-4878-a5dd-5ceca66f5473)

I think the best approach would be to cut the blue part to go around the leaves, and removes these white paths.

**Comment by GregRRoss** [comment]
White parts around leaves subtracted using path "difference" :  https://github.com/overthesun/simoc-web/pull/608

**Comment by ezio-melotti** [comment]
Before:
![image](https://github.com/overthesun/simoc-web/assets/25624924/6743d0a4-1b92-47cb-9460-9ee73d441b5c)
After:
![image](https://github.com/overthesun/simoc-web/assets/25624924/24a31555-4985-49d9-8371-2179451cc6fd)
Fixed!
